### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by Giasinit** [umbertoghio/self-hosted-expo-updates-server#1]
Buongiorno, prima di iniziare volevo ringraziarti per la condivisione del progetto.
Dunque.. sto riscontrando un problema quando faccio login.
Ho installato tutto come si deve con Docker, ma quando faccio login mi esce un errore in console: `Error: Cannot read properties of undefined (reading 'find')`, però non ho messo alcun certificato di sicurezza, quindi potrebbe essere quello il problema anche se non sembra necessario.
Attendo tuo riscontro il prima possibile
Grazie

**Comment by umbertoghio** [comment]
Ciao, grazie :-)
L'errore sembra dovuto alla creazione dell'utente Admin (parametro di docker ADMIN_PASSWORD mancante?) o alla mancata connessione con mongo. Prova a fare un down / up.
Non dovrebbero servire i certificati

**Comment by Giasinit** [comment]
Ti ringrazio per la risposta.
È la prima volta che uso mongodb, sto riscontrando dei problemi con l'utente expo e database expo, visto che non esiste. Ho importato il init.js dicendomi che è stato creato il database e l'utente, ma in realtà non crea nulla. Volevo solo chiederti due cose:
Sul file docker production cè scritto mongodb://expo@password(ora non ricordo bene):(ip):(PORTA)/expo. Ma la sintassi del mongodb non era inverso? Tra expo e password ci dovrebbe essere : e tra l'IP e password ci dovrebbe essere @.
Poi la parte della production e la parte development, qualè la differenza? Non sono un professionista in react native 😅.
Ciao.

**Comment by umbertoghio** [comment]
Ciao, ti confermo che MONGO_CONN=mongodb://utente:password@hostnameDb:27017/nomedb
verifico il progetto, probabilmente ho sbagliato a scrivere.

Prod e dev non c'entrano con react native, usa il docker dev se vuoi fare partire il progetto facendo il checkout di GitHub sul tuo computer, altrimenti puoi usare production che usa le immagini buildate da me e messe su ghcr.io.

Spero sia utile

**Comment by Giasinit** [comment]
per quanto riguarda **_feathersjs_** devo avere l'AUTH a parte?

**Comment by umbertoghio** [comment]
no, metti solo una stringa, tipo una password lunga, nell'env FEATHERS_AUTH_SECRET, serve per firmare i token JWT

**Comment by Giasinit** [comment]
e per quanto riguarda **_mongoinit/init.js_** come devo fare? devo usare un database di nome `expo` e poi creare un utente per il database `updater`?

**Comment by umbertoghio** [comment]
inserisci un utente, password e nome DB a tua preferenza dentro init.js, in questo modo quando mongo parte e non trova nessun file / db sul disco procederà a creare un DB con un utente e password automaticamente. Inserisci poi questi parametri in MONGO_CONN

**Comment by Giasinit** [comment]
ora mi da 
`Error: not authorized on expo to execute command { find: "users", filter: { username: "admin" }, limit: 1, lsid: { id: UUID("23a65728-7f4e-4ce1-bac7-c9b04c06fb9c") }, $db: "expo" }`

**Comment by umbertoghio** [comment]
ok, al primo avvio può succedere, prova a riavviare docker.
admin é l'utente dell'applicazione salvato nella collection users. Dovrebbe creartelo in automatico al primo avvio

**Comment by Giasinit** [comment]
niente, ti ricordo che sto usando aaPanel.

**Comment by umbertoghio** [comment]
puoi girarmi per email o allegare il docker-compose.yml che verifico?

**Comment by Giasinit** [comment]
```
version: '3.7'
services:
  self_hosted_expo_updates_server_api:
    image: ghcr.io/umbertoghio/self-hosted-expo-updates-server-api:latest
    container_name: self_hosted_expo_updates_server_api
    restart: always
    depends_on:
      - self_hosted_expo_updates_server_db
    volumes:
      - ./updates:/updates # This will store the unzipped updates
      - ./uploads:/uploads # This will hold a copy of the publishes in a zip format
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Rome # Timezone
      - FEATHERS_AUTH_SECRET=EnterHereYourCustomSecret # Custom secret for feathers authentication and JWT generation
      - MONGO_CONN=mongodb://expo:myRegularUserPassw@185.25.204.243:27017/expo # MongoDB connection string, see mongoinit/init.js
      - ADMIN_PASSWORD=devserver # Password for the admin user
      - UPLOAD_KEY=abc123def456 # Key used in the expo publish custom script
      - NODE_ENV=production
      - PUBLIC_URL=http://185.25.204.243:8080 # Public URL for the server, better if it is a https URL
      - DASBHOARD_THROTTLE_MSEC=5000 # No more than one refresh every 5 seconds fror the dashboard
  self_hosted_expo_updates_server_web:
    image: ghcr.io/umbertoghio/self-hosted-expo-updates-server-web:latest
    container_name: self_hosted_expo_updates_server_web
    restart: always
    depends_on:
      - self_hosted_expo_updates_server_api
    ports:
      - 8080:80 # Put this behind an https reverse proxy if you want to use it in production
    environment:
      - API_BASE_URL=http://185.25.204.243:3000 # URL of the API server

  self_hosted_expo_updates_server_db:
    container_name: self_hosted_expo_updates_server_db
    image: mongo:4.2.2
    platform: linux/amd64
    restart: always
    ports:
      - 27017:27017
    volumes:
      - self_hosted_mongo_data:/data/db
      - ./mongoinit:/docker-entrypoint-initdb.d/ # Set database user credenzials in mongoinit/init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=myPRODUCTIONPassword # Root/admin password for administration
      - MONGO_INITDB_DATABASE=expo
    command: mongod --bind_ip=0.0.0.0 --logpath=/dev/null


volumes:
 self_hosted_mongo_data:

```
Appena risolviamo cambio i dati.
