### ISSUE TITLE
API_BASE_URL not  changing

### ISSUE THREAD

**Issue by lukasa1993** [umbertoghio/self-hosted-expo-updates-server#18]
trying to use docker production version and web `API_BASE_URL` doesn't change url in network logs it still localhost:3000

**Comment by umbertoghio** [comment]
Hello, 
the API_BASE_URL is used by the web frontend to know where to connect to, the server always listens to localhost:3000

**Comment by lukasa1993** [comment]
yea i am referring to  front end it always goes to localhost:3000 it ignores `API_BASE_URL`  env variable

**Comment by umbertoghio** [comment]
Are you running it from inside docker?
the mechanism for the connection relies to the status script that runs the loadEnv, creating an env-config.js that is provided to the browser.
can you check the content of this file? yourwebinstance/env-config.js is it set properly?

**Comment by lukasa1993** [comment]
this is how i run it
    
```  
expo_update_web:
    image: ghcr.io/umbertoghio/self-hosted-expo-updates-server-web:latest
    user: root
    container_name: expo_update_web
    restart: always
    volumes:
      - ./expo/web:/expo
    environment:
      - API_BASE_URL=https://expo.example.com
      - ENVIRONMENT=production
    networks:
      - lnh
    command: /expo/start.sh

 ```
    
i don't see `env-config.js` file inside docker container at least not at root level

**Comment by umbertoghio** [comment]
Probably this part is missing from your start.sh

<img width="459" alt="image" src="https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/25666241/d79cc053-7872-4727-bb91-7729251f725e">

the loadEnv script generates the env-config.js , then places it in the root folder to be picked up by the browser

**Comment by lukasa1993** [comment]
oh if i cat `/usr/share/nginx/html/env-config.js`

it has this 

```
window._env_ = { API_BASE_URL: 'http://localhostu:3000', ENVIRONMENT: 'development' }
```

**Comment by EliotAmn** [comment]
Simple question, why we are constrained to use an Nginx variable ? Why not simply pass the api url with the web server of the frontend? I use NginxProxyManager, and it's not verry easy to setup. Thank you also for this verry useful tool :)

**Comment by umbertoghio** [comment]
Hello, 
@lukasa1993 sorry, I missed your last message, have you managed to solve it?

@EliotAmn 
It is not an nginx variable,  the variable is set in the env of the docker running the web server, on startup this url is picked up and set inside a .JS file that is sent to the user's browser. 
So this is how the JS running in the browser knows where to connect to.

Feel free to fork the project and hardcode your URL in the JS client.

Hope that helps

**Comment by lukasa1993** [comment]
> Hello, 
> 
> @lukasa1993 sorry, I missed your last message, have you managed to solve it?
> 
> 
> 
> @EliotAmn 
> 
> It is not an nginx variable,  the variable is set in the env of the docker running the web server, on startup this url is picked up and set inside a .JS file that is sent to the user's browser. 
> 
> So this is how the JS running in the browser knows where to connect to.
> 
> 
> 
> Feel free to fork the project and hardcode your URL in the JS client.
> 
> 
> 
> Hope that helps
> 
> 

not with config i edited container manually but with config i couldn't solve it

**Comment by EliotAmn** [comment]
This is an extract of my production docker-compose.yml
```
self_hosted_expo_updates_server_web:
    image: ghcr.io/umbertoghio/self-hosted-expo-updates-server-web:latest
    container_name: self_hosted_expo_updates_server_web
    restart: always
    depends_on:
      - self_hosted_expo_updates_server_api
    ports:
      - 4748:8080 # Put this behind an https reverse proxy if you want to use it in production
    environment:
      - API_BASE_URL=https://to-api.my-private-domain.fr # URL of the API server
```

But : 

![image](https://github.com/user-attachments/assets/3235d93d-47d2-497a-bebf-7ff87ebcc3eb)

Yes i can edit js files directly, but i want to sometime pull the repo, and it can cause conflicts issues.
